### ISSUE TITLE
Update dependencies to support React 18

### ISSUE THREAD

**Issue by miguelvictor** [instantcommerce/next-password-protect#52]
**Is your feature request related to a problem? Please describe.**
Installing on new next.js apps gives a warning of incorrect peer dependency because `create-next-app` now uses react 18.

**Describe the solution you'd like**
Update package dependencies.

**Describe alternatives you've considered**
Installing it as is (ignoring the warning).

**Additional context**
None

**Comment by icebearlabs** [comment]
The issue with the "alternative approach" is, that it throws errors in production and you can't deploy at all. 

This means, that de facto we can't use this package.

**Comment by rludvig** [comment]
I see a fix has been merged, any chance of doing a new release?

**Comment by rafaelderolez** [comment]
Would love for this to get published to npm as well!

**Comment by BJvdA** [comment]
Sorry for the wait, it has been released (we also renamed, so npm link now is https://www.npmjs.com/package/next-password-protect)
